language: julia

os:
  - linux

julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false
  
name: Julia TagBot
uses: JuliaRegistries/TagBot@v1.5.3
 
  
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

