name = "DiffPrivacy"
uuid = "53714aee-e5d1-4d1b-abff-f814f0c675a5"
authors = ["Rakshit Naidu <rakshit.naidu07@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
