site_name:        DiffPrivacy.jl
repo_url:         https://github.com/r0cketr1kky/DiffPrivacy.jl
site_description: Differential Privacy library
site_author:      r0cketr1kky

theme:
  name: 'material'

extra_css:
  - assets/Documenter.css
  - assets/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

# nav:
#   - Home: index.md
